name: "HCL AppScan SAST - Personal Scans"
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  scan:
    runs-on: ubuntu-latest
    needs: checkout
    steps:

      - name: Run AppScan SAST Scan
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@v1.0.7
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          application_id: ${{vars.ASOC_APPID}}
          #scan_build_outputs: true
          personal_scan: true
          scan_name: "Personal Scan - ${{ github.ref_name }}_${{ github.sha }}_${{ github.run_id }}"